<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="FrmSindico.aspx.cs" Inherits="condominios.FrmSindico" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">

    <asp:Panel runat="server" ID="pnlCadastro" Visible="true">
        <form id="form1" runat="server" class="form_settings">

            <ul>

                <li>
                    <asp:Label Text="Id" ID="lbId" runat="server" />
                    <asp:TextBox ID="txId" Enabled="false" Text="" runat="server" />
                </li>

                <li>
                    <asp:Label Text="Endereco" ID="lbEndereco" runat="server" />
                    <asp:DropDownList ID="dlEndereco" runat="Server" />
                </li>

                <li>
                    <asp:Label Text="Condomínio" ID="lbCondominio" runat="server" />
                    <asp:DropDownList ID="dlCondominio" runat="Server" />
                </li>

                <li>
                    <asp:Label Text="Nome" ID="lbNome" runat="server" />
                    <asp:TextBox ID="txNome" Text="" runat="server" />
                </li>

                <li>
                    <asp:Label Text="CPF" ID="lbCPF" runat="server" />
                    <asp:TextBox ID="txCPF" Text="" runat="server" />
                </li>

                <li>
                    <asp:Label Text="RG" ID="lbRg" runat="server" />
                    <asp:TextBox ID="txRg" Text="" runat="server" />
                </li>


                <li>
                    <asp:Button ID="btnCadastrar" runat="server" Text="Salvar" OnClick="btnCadastrar_Click" />
                </li>

            </ul>

            <asp:GridView ID="gridView1" runat="server" AutoGenerateEditButton="true"
                AutoGenerateDeleteButton="true" OnRowEditing="EditRowButton_Click" OnRowDeleting="DeleteRowButton_Click" />
        </form>
    </asp:Panel>

</asp:Content>
